osx_image: xcode8.1
language: objective-c
cache:
  - bundler
  - cocoapods

podfile: ios/analytics/Podfile
env: SAMPLE=Analytics

matrix:
  include:
  - podfile: ios/signin/Podfile
    env: SAMPLE=SignIn

rvm: 2.3.1
before_install:
  - gem uninstall cocoapods -a
  - gem install cocoapods -v '1.1.1'
  - gem install xcpretty
  - cd ios/$SAMPLE
  - pod install --repo-update
  - sed -i '' 's/YOUR_REVERSED_CLIENT_ID/com.googleusercontent.apps.123456789000-hjugbg6ud799v4c49dim8ce2usclthar/' "$SAMPLE"Example/Info.plist
  - cd -

script: ios/test.sh
